### ISSUE TITLE
Weird shapes in "ADN 14 paires de bases" 

### ISSUE THREAD

**Issue by Futuray-pgm** [ppillot/libmol#13]
![sketch-1697276659083.png](https://github.com/ppillot/libmol/assets/123812211/a467c52b-b94e-4d5b-a3ca-90e50b96c1e9)

Are the rounded shapes normal in a DNA molecule, or is it an error?

**Comment by ppillot** [comment]
Yes, it's a known bug in the NGL rendering library. The code that computes the spline for the ribbon can create these glitches on some nucleic structure.
